# Лабораторна робота "Операції над масивами NumPy"

__Метою__ лабораторної роботи є набуття практичних навичок та закріплення теоретичних знань по обробці великих однорідних наборів даних які розташовані у вигляді масивів бібліотеки __NumPy__.

Виконати послідовно завдання в секціях, попередню засвоївши наведені приклади
В завданнях продовжити написання коду замість `...`. 

__Імена змінних в завданнях змінювати не можна!__

### Предвстановлення

In [1]:
# Імпортувати бібліотеку numpy з аліасом np
import numpy as np

In [2]:
# Вивід таблиці відповідності кодів типів даних в NumPy
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

dtypes

Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

## 1. Створення та інспектування _np-массивів_

### ПРИКЛАДИ

In [3]:
# Створити 1-вимірний масив з 5 цілочисельних елементів 
arr = np.array([23, 42, 13, 7, 0])

In [4]:
# Інспектування массива
np.info(arr)

class:  ndarray
shape:  (5,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x12d26a96750
byteorder:  little
byteswap:  False
type: int32


In [5]:
# створити 2-мірний масив з цілим типом даних у 2-х байтовому форматі
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
# створити масив із  значень в інтервалі 0 - 20 з кроком 2
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [7]:
# створити масив із 20 рівномірно розміщених значень в інтервалі 0 - 10 
# np.linspace(start, stop, num_of_elements) 
arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [8]:
# створити масив 3х3 випадкових значень 
arr = np.random.rand(3, 3)
print(arr)

[[0.27443557 0.26040267 0.14743098]
 [0.63913527 0.51689489 0.52789408]
 [0.80201056 0.82499729 0.68718648]]


In [9]:
# створення нульвих, одиничних та заповнених масивів
zeros = np.zeros((2,3), dtype='i4')
print(zeros)
ones = np.ones((2,3))
print(ones)
filled = np.full((2,3), 123)
print(filled)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[123 123 123]
 [123 123 123]]


In [10]:
print(arr, end="\n...\n")
# інспектування типу массиву `dtype`
print(arr.dtype)
# інспектування розмірності массиву `shape`
print(arr.shape)
# інспектування довжини масиву `len`
print(len(arr))
# інспектування кількості вимірів масиву `ndim`
print(arr.ndim)
# інспектування кількості елементів в масиві `size`
print(arr.size)
# інспектування коількості байтів на елемент `itemsize`
print(arr.itemsize)
# інспектування кількості пам'яти під масив `nbytes`
print(arr.nbytes)

[[0.27443557 0.26040267 0.14743098]
 [0.63913527 0.51689489 0.52789408]
 [0.80201056 0.82499729 0.68718648]]
...
float64
(3, 3)
3
2
9
8
72


In [11]:
arr.__sizeof__()

200

### ЗАВДАННЯ 1

In [12]:
### ЗАВДАННЯ 1.1: створити та проінспектувати масив 3х4 з ім'ям arr1_1, який містить числа з плавоючою точкою 
arr1_1 = np.random.rand(3, 4)
np.info(arr1_1)
print(arr1_1)

class:  ndarray
shape:  (3, 4)
strides:  (32, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x12d1ba977b0
byteorder:  little
byteswap:  False
type: float64
[[0.73210995 0.84754805 0.87374596 0.53588456]
 [0.87734484 0.16422782 0.19505841 0.36869636]
 [0.19677791 0.44353849 0.53132853 0.79450297]]


In [16]:
### ЗАВДАННЯ 1.2: створити одномірний масив з 5 строкових елементів
arr1_2 = np.array(['type', 'file', 'run', 'victory', 'open'])
print(arr1_2)

['type' 'file' 'run' 'victory' 'open']


In [17]:
### ЗАВДАННЯ 1.3: створити одиничний масив 3х4 чисел з плаваючою точкою
arr1_3 = np.ones((3,4), dtype='f')
print(arr1_3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 2. Перетворення форми та типу массивів

### ПРИКЛАДИ

In [18]:
# створити 2-мірний float-масив (2х5) з лінійного int-списка 
spisok = list(range(0,10))
arr = np.array(spisok)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
#преретворити форму масива `reshape` 
arr = arr.reshape((2,5))
print(arr)
print(arr.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32


In [20]:
# -- 3 перетворити тип масива `astype`
arr = arr.astype('float64')
print(arr)
print(arr.dtype)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
float64


In [21]:
# 'вирівняти' 2-мірний масив
arr = arr.flatten()
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### ЗАВДАННЯ 2

In [22]:
### ЗАВДАННЯ 2.1: створити 3-мірний масив (3х1х3) логічного 'False'
arr2_1 = np.array(["False"] * 9)
arr2_1 = arr2_1.reshape((3,1,3))
print(arr2_1)

[[['False' 'False' 'False']]

 [['False' 'False' 'False']]

 [['False' 'False' 'False']]]


In [23]:
### ЗАВДАННЯ 2.2: перетворити масив arr2_1 в 2-мірний масив (3х3) типу int
arr2_2 = arr2_1.reshape((3,3))
print(arr2_2)

[['False' 'False' 'False']
 ['False' 'False' 'False']
 ['False' 'False' 'False']]


In [24]:
### ЗАВДАННЯ 2.3: створити  2-мірний масив парних чисел в інтервалі 10-21
arr2_3 = np.arange(10, 21, 2).reshape((2,3))

print(arr2_3)

[[10 12 14]
 [16 18 20]]


## 3. Доступ до  елементів масива

### ПРИКЛАДИ

In [25]:
arr = np.array([10, 6, 7, 21, 44]) 
print(arr)

# 1-й елемент 
print(arr[0])
# 3-й елемент
print(arr[2])
# останній елемент
print(arr[-1])

[10  6  7 21 44]
10
7
44


In [26]:
# створити 2-мірний масив з цілих чисел з інтервалу 10-50
arr = np.random.randint(10, 50, (4,4))
print(arr)

[[38 16 35 47]
 [20 14 34 15]
 [34 22 17 22]
 [46 13 43 40]]


In [27]:
# отримати значення останнього елемента в 2 рядку
el = arr[1, -1]
print(el)

15


In [28]:
# отримати значення останнього рядка
vect = arr[-1]
print(vect)

[46 13 43 40]


In [29]:
# отримати `зріз` з 1 по 2 рядок
mat = arr[0:2]
print(mat)

[[38 16 35 47]
 [20 14 34 15]]


In [30]:
# вилучити 2 та 3 стовбчики `arr`
mat = arr[0:4, 1:3]
print(mat)

[[16 35]
 [14 34]
 [22 17]
 [13 43]]


In [31]:
# вилучити непарні рядки `arr`
mat = arr[0:4:2]
print(mat)

[[38 16 35 47]
 [34 22 17 22]]


In [32]:
# фільтрувати елементи масива за умовою
els = arr[arr > 20]
print(els)

[38 35 47 34 34 22 22 46 43 40]


### ЗАВДАННЯ 3

In [35]:
### ЗАВДАННЯ 3.1: створити масив 4х5 нормально розподілений випадкових чисел 3 інтервалу [10 - 100]
arr3_1 = np.linspace(10, 100, 20)
arr3_1 = arr3_1.reshape(4,5)
print(arr3_1)

[[ 10.          14.73684211  19.47368421  24.21052632  28.94736842]
 [ 33.68421053  38.42105263  43.15789474  47.89473684  52.63157895]
 [ 57.36842105  62.10526316  66.84210526  71.57894737  76.31578947]
 [ 81.05263158  85.78947368  90.52631579  95.26315789 100.        ]]


In [36]:
### ЗАВДАННЯ 3.2:  вивести 3-елемент в 2-му рядку
el3_2 = arr3_1[1, 2]
print(el3_2)

43.1578947368421


In [37]:
### ЗАВДАННЯ 3.3:  вивести 2-й рядок масива `arr3_1`
vect3_3 = arr3_1[1]
print(vect3_3)

[33.68421053 38.42105263 43.15789474 47.89473684 52.63157895]


In [38]:
### ЗАВДАННЯ 3.4:  вивести 3 колонку масива `arr3_1`
vect3_4 = arr3_1[:, 2]
print(vect3_4)

[19.47368421 43.15789474 66.84210526 90.52631579]


In [39]:
### ЗАВДАННЯ 3.5: вивести матрицю  з 2 та 3 рядка та 2 та 3 колонки масива `arr3_1`
mat3_5 = arr3_1[1:3, 1:3]
print(mat3_5)

[[38.42105263 43.15789474]
 [62.10526316 66.84210526]]


## 4. Матричні компоненти масива

### ПРИКЛАДИ

In [40]:
# створити одиничну матрицю розміру 3х3
mat = np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [41]:
# створити матрицю із заданою диагоналлю
mat = np.diag([1,2,3,4,5])
print(mat)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [42]:
# вилучити головну діагональ матриці `diag`
mat = np.random.rand(5,5)
print(mat, end="\n...\n")
print(np.diag(mat))

[[0.13287883 0.84710898 0.9606904  0.05819155 0.4711312 ]
 [0.3936546  0.05764324 0.93823113 0.35488204 0.34292617]
 [0.81820363 0.62383967 0.82206063 0.20327604 0.12807172]
 [0.29593231 0.77441762 0.34967567 0.2548191  0.7665728 ]
 [0.98871038 0.54483448 0.74606218 0.88020643 0.37848171]]
...
[0.13287883 0.05764324 0.82206063 0.2548191  0.37848171]


In [43]:
# транспонувати матрицю `mat` (https://ru.wikipedia.org/wiki/Транспонированная_матрица)
mT = np.transpose(mat)
print(mT)

[[0.13287883 0.3936546  0.81820363 0.29593231 0.98871038]
 [0.84710898 0.05764324 0.62383967 0.77441762 0.54483448]
 [0.9606904  0.93823113 0.82206063 0.34967567 0.74606218]
 [0.05819155 0.35488204 0.20327604 0.2548191  0.88020643]
 [0.4711312  0.34292617 0.12807172 0.7665728  0.37848171]]


In [44]:
# отримати детермінант матриці `det` (https://ru.wikipedia.org/wiki/Определитель)
print(np.linalg.det(mat))

-0.15734744713730756


In [45]:
# отримати зворотню матриці `det` (https://ru.wikipedia.org/wiki/Обратная_матрица)
invM = np.linalg.inv(mat)
print(invM)

[[-1.81504408  0.46181498  1.89078229  0.9816139  -0.78703621]
 [ 1.31498814 -1.63353737 -0.1575412  -0.40990907  0.726726  ]
 [ 0.72465442  0.74676442 -0.06505946 -0.70435172 -0.13005443]
 [ 1.1932323  -0.73160066 -2.02847315 -1.12719714  2.14695916]
 [-1.35495571  1.37452649  0.1331935   2.03565213 -1.08468407]]


### ЗАВАДАННЯ 4

In [46]:
# ЗАВДАННЯ 4.1: створити квадратну матрицю з 36 рівномірно розподілених цілих 
# елементів з інтервалу 100 - 200
mat4_1 = np.linspace(100, 200, 36)
mat4_1 = mat4_1.reshape(6,6)
print(mat4_1)

[[100.         102.85714286 105.71428571 108.57142857 111.42857143
  114.28571429]
 [117.14285714 120.         122.85714286 125.71428571 128.57142857
  131.42857143]
 [134.28571429 137.14285714 140.         142.85714286 145.71428571
  148.57142857]
 [151.42857143 154.28571429 157.14285714 160.         162.85714286
  165.71428571]
 [168.57142857 171.42857143 174.28571429 177.14285714 180.
  182.85714286]
 [185.71428571 188.57142857 191.42857143 194.28571429 197.14285714
  200.        ]]


In [47]:
# ЗАВДАННЯ 4.2: вивести головну діагональ матниці `mat4_1`
diag4_2 = np.diag(mat4_1)
print(diag4_2)

[100. 120. 140. 160. 180. 200.]


In [48]:
# ЗАВДАННЯ 4.3: транспонувати матрицю 'mat4_1'
trans4_3 = np.transpose(mat4_1)
print(trans4_3)

[[100.         117.14285714 134.28571429 151.42857143 168.57142857
  185.71428571]
 [102.85714286 120.         137.14285714 154.28571429 171.42857143
  188.57142857]
 [105.71428571 122.85714286 140.         157.14285714 174.28571429
  191.42857143]
 [108.57142857 125.71428571 142.85714286 160.         177.14285714
  194.28571429]
 [111.42857143 128.57142857 145.71428571 162.85714286 180.
  197.14285714]
 [114.28571429 131.42857143 148.57142857 165.71428571 182.85714286
  200.        ]]


In [49]:
# ЗАВДАННЯ 4.4: вирахувати зворотню до 'mat4_1' матрицю 
inv4_4 = np.linalg.inv(mat4_1)
inv4_4

array([[ 1.29742372e+13, -2.63882791e+13, -8.79609302e+12,
         3.95824186e+13, -1.20946279e+13, -5.27765581e+12],
       [-7.47667907e+12,  1.75921860e+13, -3.79166667e-01,
        -2.63882791e+13,  1.97912093e+13, -3.51843721e+12],
       [ 1.91315023e+13,  8.79609302e+12, -8.79609302e+12,
        -4.83785116e+13, -7.69658139e+12,  3.69435907e+13],
       [-5.71746046e+13,  3.51843721e+13,  3.51843721e+13,
         1.75921860e+13,  4.39804651e+12, -3.51843721e+13],
       [ 2.19902326e+13, -3.51843721e+13, -0.00000000e+00,
         1.75921860e+13, -4.39804651e+12, -5.27343750e-02],
       [ 1.05553116e+13, -0.00000000e+00, -1.75921860e+13,
        -0.00000000e+00, -0.00000000e+00,  7.03687442e+12]])

## 5. Операції над масивами

### ПРИКЛАДИ

In [50]:
# задати вектор з 10 елементів
vect = np.array([1, 3, 2, -3, 5, 0])

In [51]:
# вирахувати суму елеметнів
s = np.sum(vect)

# знайти мінімальний ел-т
m = np.min(vect)

# відсортувати вектор по зростанню
vs = np.sort(vect)

# знайти середнє значення
mid = np.average(vect)
...

Ellipsis

In [52]:
# матриця 3х3 сконструйована різними методами
mat = np.array([np.arange(1,4), [-2, 4, 6], np.full(3,77)])
print(mat)

[[ 1  2  3]
 [-2  4  6]
 [77 77 77]]


In [53]:
# сума по колонкам `axis=0`
s = np.sum(mat, axis=0)
print(s)

[76 83 86]


In [54]:
# мінімум по рядкам
m = np.min(mat, axis=1)
print(m)

[ 1 -2 77]


In [55]:
# збільшити ел-ти масива вдвічі
v2 = mat * 2
print(v2)

[[  2   4   6]
 [ -4   8  12]
 [154 154 154]]


In [56]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(M, N, sep="\n")

[[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [57]:
# перемножити елементи матриць M, N
K = M * N
print(K)
# або ->
K = np.multiply(N, M)
print(K)

[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]
[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]


In [58]:
# поелементний поділ
K = N / M
print(K)

[[ 1.          0.5         0.33333333]
 [ 0.5        -0.66666667  0.33333333]
 [ 0.42857143  0.375              inf]]


C:\Users\stepa\AppData\Local\Temp\ipykernel_21404\3347190385.py:2: RuntimeWarning: divide by zero encountered in divide
  K = N / M


In [59]:
# скалярне множення матриць (https://ru.wikipedia.org/wiki/Умножение_матриц)
prod = np.dot(N, M)
print(prod)

[[12  7  9]
 [24 14 18]
 [36 21 27]]


In [60]:
# возвести матрицю `prod` в ступінь 3
pmat = np.linalg.matrix_power(prod, 3)
print(pmat)

[[ 33708  19663  25281]
 [ 67416  39326  50562]
 [101124  58989  75843]]


In [61]:
# додати елементи до 1-вимірного масива
mat = np.array([1,2,3])
mat = np.append(mat, [5,6,7,8])
print(mat)

[1 2 3 5 6 7 8]


In [62]:
# вставити елемент `4` в масив після 3-го елемента
mat = np.insert(mat, 3, 4)
print(mat)

[1 2 3 4 5 6 7 8]


In [63]:
# видалити елемент з індексом 6
mat = np.delete(mat, 6)
print(mat)

[1 2 3 4 5 6 8]


In [64]:
#  копіювання та присвоювання масивів
M = np.random.randint(1, 10, 5 )
print(M)

# присвоїти масив `M` в `N`
N = M
print(N)
print(id(M), id(N))

# копіювати масив `M` в `K`
K = np.copy(M)
print(K)
print(id(M), id(K))

[5 8 1 5 5]
[5 8 1 5 5]
1293471553968 1293471553968
[5 8 1 5 5]
1293471553968 1293466664464


In [65]:
# конкатенація масивів по рядкам
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)
# по колонкам `axis = 1`
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ЗАВДАННЯ 5

In [66]:
# ЗАВДАННЯ 5.1: просумувати по рядкам масив випадкових чисел розмірностю 3х4
mat5_1 = np.random.randint(10, 20, (3,4))
print(mat5_1)
sum_mat5_1 = np.sum(mat5_1, axis=1)
print(sum_mat5_1)

[[19 16 14 16]
 [13 18 13 14]
 [19 14 18 18]]
[65 58 69]


In [67]:
# ЗАВДАННЯ 5.2: знайти мінімальний елемент матриці `sum_mat5_1`
min_mat5_1 = min(sum_mat5_1)
print(min_mat5_1)

58


In [68]:
# ЗАВДАННЯ 5.3: створити масив додавши до елементів `mat5_1`  число 100
mat5_3 = mat5_1 + 100
print(mat5_3)

[[119 116 114 116]
 [113 118 113 114]
 [119 114 118 118]]


In [69]:
# ЗАВДАННЯ 5.4: помножити матрицю `mat5_1` на головну діагональ матриці `mat5_3`
diag = np.diagonal(mat5_3)
mat5_4 = np.dot(diag, mat5_1)
print(mat5_4)

[6037 5680 5324 5680]


In [70]:
# ЗАВДАННЯ 5.5: додати справа до матриці `mat5_3` матрицю `mat5_4` 
# вивести ранг отриманої матриці
mat5_5 = np.vstack([mat5_3, mat5_4])
print(mat5_5)

[[ 119  116  114  116]
 [ 113  118  113  114]
 [ 119  114  118  118]
 [6037 5680 5324 5680]]
